--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    is_active boolean,
    badge_text character varying(255),
    created_at timestamp(6) without time zone,
    icon_name character varying(255),
    category_key character varying(255) NOT NULL,
    label character varying(255) NOT NULL,
    sort_order integer,
    updated_at timestamp(6) without time zone,
    parent_id bigint
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    sender character varying(255),
    content character varying(255),
    conversation_id character varying(255),
    sent_at timestamp without time zone
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conversations (
    id bigint NOT NULL,
    conversation_id character varying(255) NOT NULL,
    buyer_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    product_id bigint,
    last_message character varying(255),
    last_message_time timestamp without time zone,
    unread_count_buyer integer DEFAULT 0,
    unread_count_seller integer DEFAULT 0,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


ALTER TABLE public.conversations OWNER TO postgres;

--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Name: favorites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.favorites OWNER TO postgres;

--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: liquibase_test; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.liquibase_test (
    id bigint NOT NULL,
    test_message character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.liquibase_test OWNER TO postgres;

--
-- Name: liquibase_test_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.liquibase_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.liquibase_test_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_images (
    id bigint NOT NULL,
    product_id bigint,
    image_data bytea NOT NULL,
    content_type character varying(255),
    file_name character varying(255)
);


ALTER TABLE public.product_images OWNER TO postgres;

--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_measurements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_measurements (
    product_id bigint NOT NULL,
    measurement_value character varying(255),
    measurement_key character varying(255) NOT NULL
);


ALTER TABLE public.product_measurements OWNER TO postgres;

--
-- Name: product_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_tags (
    product_id bigint NOT NULL,
    tag character varying(255)
);


ALTER TABLE public.product_tags OWNER TO postgres;

--
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    title character varying(120) NOT NULL,
    description character varying(1000) NOT NULL,
    price double precision NOT NULL,
    category_id bigint NOT NULL,
    seller_id bigint NOT NULL,
    created_at timestamp without time zone,
    brand character varying(255),
    size character varying(255),
    condition character varying(255) NOT NULL,
    price_with_fees numeric(10,2),
    shipping_info character varying(255),
    status character varying(255) NOT NULL,
    view_count integer NOT NULL,
    favorite_count integer NOT NULL,
    updated_at timestamp without time zone,
    city character varying(255),
    country character varying(255),
    is_active boolean NOT NULL
);


ALTER TABLE public.products OWNER TO postgres;

--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    role character varying(255) DEFAULT 'USER'::character varying,
    phone character varying(255),
    address text,
    city character varying(255),
    country character varying(255),
    profile_image character varying(500),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    state character varying(255),
    street character varying(255),
    zip_code character varying(255),
    auth_provider character varying(255),
    is_enabled boolean,
    is_guest boolean,
    profile_picture_url character varying(255),
    provider_id character varying(255),
    CONSTRAINT users_auth_provider_check CHECK (((auth_provider)::text = ANY ((ARRAY['EMAIL'::character varying, 'GOOGLE'::character varying, 'FACEBOOK'::character varying, 'APPLE'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, is_active, badge_text, created_at, icon_name, category_key, label, sort_order, updated_at, parent_id) FROM stdin;
1	t	\N	2025-07-14 19:42:10.387162	human-female	femmes	Femmes	0	2025-07-14 19:42:10.387172	\N
2	t	\N	2025-07-14 19:42:10.394199	human-male	hommes	Hommes	0	2025-07-14 19:42:10.394208	\N
3	t	\N	2025-07-14 19:42:10.395339	diamond-stone	createurs	Articles de créateurs	0	2025-07-14 19:42:10.395345	\N
4	t	\N	2025-07-14 19:42:10.39672	baby-face-outline	enfants	Enfants	0	2025-07-14 19:42:10.396727	\N
5	t	\N	2025-07-14 19:42:10.398347	lamp	maison	Maison	0	2025-07-14 19:42:10.410427	\N
6	t	\N	2025-07-14 19:42:10.414154	power	electronique	Électronique	0	2025-07-14 19:42:10.414166	\N
7	t	\N	2025-07-14 19:42:10.415978	book-open-page-variant	divertissement	Divertissement	0	2025-07-14 19:42:10.415984	\N
8	t	Nouveau	2025-07-14 19:42:10.417071	star-outline	loisirs	Loisirs et collections	0	2025-07-14 19:42:10.417077	\N
9	t	\N	2025-07-14 19:42:10.418748	tennis-ball	sport	Sport	0	2025-07-14 19:42:10.418755	\N
10	t	\N	2025-07-14 19:42:10.42615	human-female	vetements	Vêtements	0	2025-07-14 19:42:10.42616	1
11	t	\N	2025-07-14 19:42:10.428855	shoe-heel	chaussures	Chaussures	0	2025-07-14 19:42:10.428862	1
12	t	\N	2025-07-14 19:42:10.430715	bag-personal-outline	sacs	Sacs	0	2025-07-14 19:42:10.430723	1
13	t	\N	2025-07-14 19:42:10.433681	necklace	accessoires	Accessoires	0	2025-07-14 19:42:10.433689	1
14	t	\N	2025-07-14 19:42:10.435272	bottle-tonic-outline	beaute	Beauté	0	2025-07-14 19:42:10.43528	1
15	t	\N	2025-07-14 19:42:10.439085	\N	manteaux	Manteaux et vestes	0	2025-07-14 19:42:10.439093	10
16	t	\N	2025-07-14 19:42:10.441327	\N	sweats	Sweats et sweats à capuche	0	2025-07-14 19:42:10.441335	10
17	t	\N	2025-07-14 19:42:10.443027	\N	robes	Robes	0	2025-07-14 19:42:10.443048	10
18	t	\N	2025-07-14 19:42:10.444504	\N	jupes	Jupes	0	2025-07-14 19:42:10.444538	10
19	t	\N	2025-07-14 19:42:10.445753	\N	hauts	Hauts et t-shirts	0	2025-07-14 19:42:10.445759	10
\.


--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_message (id, sender, content, conversation_id, sent_at) FROM stdin;
\.


--
-- Data for Name: conversations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.conversations (id, conversation_id, buyer_id, seller_id, product_id, last_message, last_message_time, unread_count_buyer, unread_count_seller, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
create-products-table	souqly	db/changelog/db.changelog-2024-07-01-product.xml	2025-07-14 19:26:52.197233	1	EXECUTED	9:c53b377b91ffca993c791d64045fa3db	createTable tableName=products		\N	4.27.0	\N	\N	2521212157
create-product-images-blob-table	souqly	db/changelog/db.changelog-2024-07-01-product-images-blob.xml	2025-07-14 19:26:52.209679	2	EXECUTED	9:c49f735d7d6263041709d8a92162e58e	createTable tableName=product_images; addForeignKeyConstraint baseTableName=product_images, constraintName=fk_product_images_product_blob, referencedTableName=products		\N	4.27.0	\N	\N	2521212157
2024-07-01-update-products	souqly	db/changelog/db.changelog-2024-07-01-update-products.xml	2025-07-14 19:26:52.22844	3	EXECUTED	9:e03f5b639295e3e956206a1c26f724f0	addColumn tableName=products; addColumn tableName=products; addColumn tableName=products; addColumn tableName=products; addColumn tableName=products; addColumn tableName=products; addColumn tableName=products; addColumn tableName=products; addColu...		\N	4.27.0	\N	\N	2521212157
test-postgres-compatibility	souqly	db/changelog/db.changelog-test-postgres.xml	2025-07-14 19:26:52.239546	4	EXECUTED	9:6d991db36f3d6eb3dfa9eaedbb589ae8	createTable tableName=liquibase_test; insert tableName=liquibase_test	Test de compatibilité PostgreSQL avec Liquibase	\N	4.27.0	prod	\N	2521212157
2025-07-03-fix-product-columns	toufik	db/changelog/db.changelog-2025-07-03-fix-product-columns.xml	2025-07-14 19:26:52.250832	5	EXECUTED	9:9c24abe05d7b9ef413cc4eb6c43918c1	modifyDataType columnName=title, tableName=products; modifyDataType columnName=description, tableName=products		\N	4.27.0	\N	\N	2521212157
2025-01-27-add-product-location	toufik	db/changelog/db.changelog-2025-01-27-add-product-location.xml	2025-07-14 19:26:52.260701	6	EXECUTED	9:82c929d77b591bd1100d0ad157f40427	addColumn tableName=products; update tableName=products		\N	4.27.0	\N	\N	2521212157
2024-07-04-add-product-city-country	ai-assistant	db/changelog/db.changelog-2024-07-04-add-product-city-country.xml	2025-07-14 19:26:52.266275	7	EXECUTED	9:e54735b13bf13c6ad1833c6dbfdc7ef7	addColumn tableName=products		\N	4.27.0	\N	\N	2521212157
remove-latitude-longitude-from-products	souqly	db/changelog/db.changelog-2025-07-07-remove-product-lat-lng.xml	2025-07-14 19:26:52.280443	8	EXECUTED	9:371e6c9c369c55bb0d0f46a2e58b2228	dropColumn columnName=latitude, tableName=products; dropColumn columnName=longitude, tableName=products		\N	4.27.0	\N	\N	2521212157
remove-locationname-from-products	souqly	db/changelog/db.changelog-2025-07-07-remove-product-locationname.xml	2025-07-14 19:26:52.283852	9	EXECUTED	9:9eafb21af03097ebc88cc67edd9d5072	dropColumn columnName=location_name, tableName=products		\N	4.27.0	\N	\N	2521212157
create-chat-message-table	cursor-ai	db/changelog/add_chat_message_table.xml	2025-07-14 19:26:52.296269	10	EXECUTED	9:250ebce35f265ffc68002f702822e767	createTable tableName=chat_message		\N	4.27.0	\N	\N	2521212157
create-users-table	souqly	db/changelog/db.changelog-2024-07-01-create-users.xml	2025-07-14 19:42:05.495699	11	EXECUTED	9:2c43d2548d30ffcf9d0c2c4f15f7ee1c	createTable tableName=users; createIndex indexName=idx_users_email, tableName=users; createIndex indexName=idx_users_role, tableName=users		\N	4.27.0	\N	\N	2522125456
create-conversations-table	cursor-ai	db/changelog/add_conversations_table.xml	2025-07-14 19:42:05.520374	12	EXECUTED	9:2e098a89edd5299605d9fb5314db58b9	createTable tableName=conversations; createIndex indexName=idx_conversations_buyer_id, tableName=conversations; createIndex indexName=idx_conversations_seller_id, tableName=conversations; createIndex indexName=idx_conversations_product_id, tableNa...		\N	4.27.0	\N	\N	2522125456
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: favorites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.favorites (id, created_at, product_id, user_id) FROM stdin;
\.


--
-- Data for Name: liquibase_test; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.liquibase_test (id, test_message, created_at) FROM stdin;
1	Liquibase fonctionne avec PostgreSQL !	2025-07-14 19:26:52.231435
\.


--
-- Data for Name: product_images; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_images (id, product_id, image_data, content_type, file_name) FROM stdin;
\.


--
-- Data for Name: product_measurements; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_measurements (product_id, measurement_value, measurement_key) FROM stdin;
\.


--
-- Data for Name: product_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_tags (product_id, tag) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, title, description, price, category_id, seller_id, created_at, brand, size, condition, price_with_fees, shipping_info, status, view_count, favorite_count, updated_at, city, country, is_active) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, first_name, last_name, role, phone, address, city, country, profile_image, is_active, created_at, updated_at, state, street, zip_code, auth_provider, is_enabled, is_guest, profile_picture_url, provider_id) FROM stdin;
1	admin@souqly.com	$2a$10$0ihYbtD1tiHgHhZuC5ytRunXuraUbWn.LJiPh55xYtbYhoSR4gnAu	Admin	Souqly	ADMIN	\N	\N	\N	\N	\N	t	2025-07-14 19:42:10.244559	2025-07-14 19:42:10.244673	\N	\N	\N	EMAIL	t	f	\N	\N
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 19, true);


--
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 1, false);


--
-- Name: conversations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.conversations_id_seq', 1, false);


--
-- Name: favorites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.favorites_id_seq', 1, false);


--
-- Name: liquibase_test_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.liquibase_test_id_seq', 1, true);


--
-- Name: product_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_images_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_conversation_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_conversation_id_key UNIQUE (conversation_id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: liquibase_test liquibase_test_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.liquibase_test
    ADD CONSTRAINT liquibase_test_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: product_measurements product_measurements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_measurements
    ADD CONSTRAINT product_measurements_pkey PRIMARY KEY (product_id, measurement_key);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: categories ukcxufxt1et9gk5oawk9y485mhr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT ukcxufxt1et9gk5oawk9y485mhr UNIQUE (category_key);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_conversations_buyer_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_conversations_buyer_id ON public.conversations USING btree (buyer_id);


--
-- Name: idx_conversations_product_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_conversations_product_id ON public.conversations USING btree (product_id);


--
-- Name: idx_conversations_seller_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_conversations_seller_id ON public.conversations USING btree (seller_id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: product_tags fk5rk6s19k3risy7q7wqdr41uss; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_tags
    ADD CONSTRAINT fk5rk6s19k3risy7q7wqdr41uss FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: conversations fk_conversations_buyer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_conversations_buyer FOREIGN KEY (buyer_id) REFERENCES public.users(id);


--
-- Name: conversations fk_conversations_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_conversations_product FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: conversations fk_conversations_seller; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT fk_conversations_seller FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: product_images fk_product_images_product_blob; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fk_product_images_product_blob FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products fkbgw3lyxhsml3kfqnfr45o0vbj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkbgw3lyxhsml3kfqnfr45o0vbj FOREIGN KEY (seller_id) REFERENCES public.users(id);


--
-- Name: product_measurements fkih6310y1wfs6nrom786ih8ky8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_measurements
    ADD CONSTRAINT fkih6310y1wfs6nrom786ih8ky8 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: products fkog2rp4qthbtt2lfyhfo32lsw9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: categories fksaok720gsu4u2wrgbk10b5n8d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fksaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES public.categories(id);


--
-- PostgreSQL database dump complete
--

